services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8088"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.3
    ports:
      - 8088:8088
      - 50051:50051
    volumes:
      - dinosaur_page:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true" # Not for production
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_API_BASED_MODULES: "true"
      CLUSTER_HOSTNAME: "node1"
volumes:
  dinosaur_page: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /aux/src/tinker/scratch/nbs/rag/wiki/api/weaviate_data
