services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.11.1"
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - dinosaur_page_elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10

volumes:
  dinosaur_page_elasticsearch: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /aux/src/tinker/scratch/nbs/rag/wiki/api/6a_elasticsearch/data

