services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.11.1"
    ports:
      - 9200:9200
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - dinosaur_page_2index_elasticsearch:/usr/share/elasticsearch/data
    healthcheck:
      test: curl --fail http://localhost:9200/_cat/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 10

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8088"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.3
    ports:
      - 8088:8088
      - 50051:50051
    volumes:
      - dinosaur_page_2index_weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true" # Not for production
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_API_BASED_MODULES: "true"
      CLUSTER_HOSTNAME: "node1"

volumes:
  dinosaur_page_2index_elasticsearch:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /aux/src/tinker/scratch/nbs/rag/wiki/api/6b_indexing_2_stores/edata
  dinosaur_page_2index_weaviate:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /aux/src/tinker/scratch/nbs/rag/wiki/api/6b_indexing_2_stores/wdata
